-- Tạo bảng Players
CREATE TABLE players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  number INT,
  position TEXT, -- 'Goalkeeper', 'Defender', 'Midfielder', 'Forward'
  nationality TEXT DEFAULT 'VN',
  image TEXT,
  height INT, -- cm
  weight INT, -- kg
  dob DATE,
  strengths TEXT,
  weaknesses TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tạo bảng Matches
CREATE TABLE matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season INT NOT NULL, -- Ví dụ: 2026
  date DATE NOT NULL,
  time TIME NOT NULL,
  stadium TEXT,
  opponent TEXT NOT NULL,
  opponent_logo TEXT,
  is_home BOOLEAN DEFAULT TRUE,
  home_score INT DEFAULT 0,
  away_score INT DEFAULT 0,
  status TEXT DEFAULT 'Upcoming', -- 'Upcoming', 'Finished', 'Live'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tạo bảng Match Stats (Ghi bàn, kiến tạo, MOTM cho từng trận)
CREATE TABLE match_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
  player_id BIGINT REFERENCES players(id) ON DELETE CASCADE,
  goals INT DEFAULT 0,
  assists INT DEFAULT 0,
  own_goals INT DEFAULT 0,
  is_motm BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tạo bảng Match Votes (Điểm danh)
CREATE TABLE match_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
  player_name TEXT NOT NULL, -- Người dùng nhập tên hoặc chọn từ list
  is_going BOOLEAN DEFAULT TRUE,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Insert dữ liệu mẫu (Sample Data)
INSERT INTO players (name, number, position, nationality, image) VALUES
('Nguyễn Văn A', 10, 'Forward', 'VN', 'https://api.dicebear.com/7.x/avataaars/svg?seed=A'),
('Trần Văn B', 4, 'Defender', 'VN', 'https://api.dicebear.com/7.x/avataaars/svg?seed=B'),
('Lê Văn C', 1, 'Goalkeeper', 'VN', 'https://api.dicebear.com/7.x/avataaars/svg?seed=C');

INSERT INTO matches (season, date, time, stadium, opponent, status) VALUES
(2026, '2026-02-01', '17:30', 'Sân Mỹ Đình', 'FC Barcelona Fake', 'Upcoming');
